version: 0.1

environment_variables:
  plaintext:
    HUGO_VERSION: "0.25.1"
    
phases:
  install:
    commands:                                                                 
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - tar -xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - mv hugo /usr/bin/hugo
      - cd - 
      - rm -rf /tmp/*
  build:
    commands:
      - rm -rf public
      - hugo
      - find public/ -name "*.css" -exec gzip {} \; -exec mv {}.gz {} \;
      - find public/ -name "*.js" -exec gzip {} \; -exec mv {}.gz {} \;
      - sleep 5
  post_build:
    commands:
      - aws s3 sync --delete public s3://pragmatic.test --region eu-central-1 --cache-control max-age=604800
      - aws s3 cp s3://pragmatic.test/css/ s3://pragmatic.test/css/ --recursive --metadata-directive REPLACE --cache-control max-age=604800,public --content-encoding 'gzip'  --acl public-read
      - aws s3 cp s3://pragmatic.test/js/ s3://pragmatic.test/js/ --recursive --metadata-directive REPLACE --cache-control max-age=604800,public --content-encoding 'gzip'  --acl public-read
      - echo Build completed on `date`
